/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemkasir;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author candr
 */
public class Transaksi2 extends javax.swing.JFrame {
    String kodeBarang;
    String namaBarang;
    int hargaJual;
    String merk;
    int quantity;
    int stock;
    double discount = 0;
    int poin = 0;
    
    Connection connection = DatabaseConnection.getConnection();
    /**
     * Creates new form Transaksi2
     */
    public Transaksi2() {
        initComponents();
    }
    
    public int hitungPoin(){
        return this.hitungTotalItem()/5000;
    }
    
    public int hitungTotalItem(){
        int totalItem = 0;
        DefaultTableModel model = (DefaultTableModel) tabelListBarang.getModel();
        int rowCount = model.getRowCount();
        for(int row=0; row<rowCount; row++){
            int total = Integer.valueOf(model.getValueAt(row, 5).toString());
            totalItem += total;
        }
        return totalItem;
    }
    public double hitungTotalBelanja(){
        double totalBelanja = this.hitungTotalItem() - this.hitungTotalItem()*this.discount;
        return totalBelanja;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputKodeBarang = new javax.swing.JTextField();
        inputNamaBarang = new javax.swing.JTextField();
        inputMerk = new javax.swing.JTextField();
        inputHarga = new javax.swing.JTextField();
        inputQuantity = new javax.swing.JTextField();
        buttonCari = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buttonTambah = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelListBarang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kategori = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        inputIdMember = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        inputTotalItem = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        inputDiscount = new javax.swing.JTextField();
        inputTotalBelanja = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        inputPembayaran = new javax.swing.JTextField();
        buttonBayar = new javax.swing.JButton();
        inputKembalian = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        inputPoin = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(246, 244, 241));

        jLabel3.setText("Tanggal");

        jLabel4.setText("Kode Barang");

        jLabel5.setText("Nama Barang");

        jLabel6.setText("Merek");

        jLabel7.setText("Harga");

        jLabel8.setText("Jumlah");

        inputKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKodeBarangActionPerformed(evt);
            }
        });

        inputNamaBarang.setEditable(false);

        inputMerk.setEditable(false);
        inputMerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMerkActionPerformed(evt);
            }
        });

        inputHarga.setEditable(false);
        inputHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHargaActionPerformed(evt);
            }
        });

        buttonCari.setBackground(new java.awt.Color(0, 51, 204));
        buttonCari.setForeground(new java.awt.Color(255, 255, 255));
        buttonCari.setText("Cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        jLabel9.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("List Barang");

        buttonTambah.setBackground(new java.awt.Color(0, 102, 102));
        buttonTambah.setForeground(new java.awt.Color(255, 255, 255));
        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tabelListBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Merek", "Harga", "Qty", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelListBarang.getTableHeader().setReorderingAllowed(false);
        tabelListBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelListBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelListBarang);
        if (tabelListBarang.getColumnModel().getColumnCount() > 0) {
            tabelListBarang.getColumnModel().getColumn(0).setResizable(false);
            tabelListBarang.getColumnModel().getColumn(1).setResizable(false);
            tabelListBarang.getColumnModel().getColumn(2).setResizable(false);
            tabelListBarang.getColumnModel().getColumn(3).setResizable(false);
            tabelListBarang.getColumnModel().getColumn(4).setResizable(false);
            tabelListBarang.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TOTAL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel11)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Kategori");

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Non-member", "Member" }));
        kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriActionPerformed(evt);
            }
        });

        jLabel12.setText("Id Member");

        inputIdMember.setEditable(false);
        inputIdMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdMemberActionPerformed(evt);
            }
        });
        inputIdMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputIdMemberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputIdMemberKeyReleased(evt);
            }
        });

        jLabel13.setText("Total Item");

        inputTotalItem.setEditable(false);
        inputTotalItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTotalItemActionPerformed(evt);
            }
        });

        jLabel14.setText("Total Disc");

        jLabel15.setText("Total Belanja");

        inputDiscount.setEditable(false);
        inputDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDiscountActionPerformed(evt);
            }
        });

        inputTotalBelanja.setEditable(false);

        jLabel17.setText("Pembayaran");

        inputPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPembayaranActionPerformed(evt);
            }
        });

        buttonBayar.setBackground(new java.awt.Color(0, 102, 102));
        buttonBayar.setForeground(new java.awt.Color(255, 255, 255));
        buttonBayar.setText("Bayar");
        buttonBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBayarActionPerformed(evt);
            }
        });

        jLabel18.setText("Kembalian");

        inputPoin.setEditable(false);
        inputPoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPoinActionPerformed(evt);
            }
        });

        jLabel19.setText("Bonus Poin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(inputQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputHarga, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputMerk, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputNamaBarang, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(inputKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buttonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputIdMember, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel17)))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputTotalBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(inputPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonBayar))
                                    .addComponent(inputKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(inputTotalItem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputPoin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                                .addContainerGap())))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(buttonTambah)
                .addGap(47, 47, 47)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(inputKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCari))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(inputNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(inputMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(inputQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonTambah)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(inputIdMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(inputTotalItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputPoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(inputDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(inputTotalBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBayar)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(302, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transaksi");

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 810, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKodeBarangActionPerformed

    private void inputMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMerkActionPerformed

    private void inputHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHargaActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) tabelListBarang.getModel();

        String harga = String.valueOf(hargaJual);
        int jumlah = Integer.valueOf(inputQuantity.getText());
        if(jumlah<=stock){
            String jumlah2 = String.valueOf(jumlah);
            int total = hargaJual * jumlah;
            String total2 = String.valueOf(total);

            String tableData[] = {kodeBarang, namaBarang, merk, harga, jumlah2, total2};
            tableModel.addRow(tableData);
            stock-=jumlah;
            inputTotalItem.setText(String.valueOf(this.hitungTotalItem()));
            inputTotalBelanja.setText(String.valueOf(this.hitungTotalBelanja()));
            
            inputKodeBarang.setText("");
            inputNamaBarang.setText("");
            this.inputMerk.setText("");
            this.inputHarga.setText("");
            this.inputQuantity.setText("");
        }else{
            JOptionPane.showMessageDialog(this, "Jumlah barang melebihi stock", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriActionPerformed
        if(kategori.getSelectedItem().toString().equals("Member")){
            inputIdMember.setEditable(true);
        }else{
            inputIdMember.setEditable(false);
            inputIdMember.setText("");
        }
        
    }//GEN-LAST:event_kategoriActionPerformed

    private void inputIdMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdMemberActionPerformed
        try{
            Statement statement = connection.createStatement();
            String sql = "SELECT * FROM member";
            ResultSet result = statement.executeQuery(sql);
            discount = 0;
            while(result.next()){
                if(result.getString("id").equals(inputIdMember.getText())){
                    discount = 10./100;
                    inputPoin.setText(String.valueOf(this.hitungPoin()));
                    break;
                }           
            }
        }catch(SQLException e){
            System.out.println(e);
        }
        NumberFormat percentFormat = NumberFormat.getPercentInstance();
        inputDiscount.setText(percentFormat.format(discount));
        inputTotalBelanja.setText(String.valueOf(this.hitungTotalBelanja()));
    }//GEN-LAST:event_inputIdMemberActionPerformed

    private void inputIdMemberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputIdMemberKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdMemberKeyReleased

    private void inputTotalItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTotalItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTotalItemActionPerformed

    private void inputDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDiscountActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        kodeBarang = inputKodeBarang.getText();
        
        // reset input awal
        namaBarang = "";
        merk = "";
        hargaJual = 0;
    
        try{
            Statement statement = connection.createStatement();
            String sql = "SELECT * FROM data_barang WHERE kode_barang="+kodeBarang;
            ResultSet result = statement.executeQuery(sql);
            
            while(result.next()){
                namaBarang = result.getString("nama_barang");
                merk = result.getString("merk");
                hargaJual = result.getInt("harga_jual");
                stock = result.getInt("quantity");
            }
            inputNamaBarang.setText(namaBarang);
            inputMerk.setText(merk);
            inputHarga.setText(Integer.toString(hargaJual));
        }catch(SQLException e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_buttonCariActionPerformed

    private void tabelListBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelListBarangMouseClicked

    }//GEN-LAST:event_tabelListBarangMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = tabelListBarang.getSelectedRow();
        if(i>=0){
            DefaultTableModel tableModel = (DefaultTableModel) tabelListBarang.getModel();
            tableModel.removeRow(i);
        }
        inputTotalItem.setText(String.valueOf(this.hitungTotalItem()));
        inputTotalBelanja.setText(String.valueOf(this.hitungTotalBelanja()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void inputIdMemberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputIdMemberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdMemberKeyPressed

    private void inputPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPembayaranActionPerformed
        Double pembayaran = Double.valueOf(inputPembayaran.getText().toString());
        Double kembalian = pembayaran - this.hitungTotalBelanja();
        inputKembalian.setText(String.valueOf(kembalian));
    }//GEN-LAST:event_inputPembayaranActionPerformed

    private void buttonBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBayarActionPerformed
        Double pembayaran = Double.valueOf(inputPembayaran.getText().toString());
        Double kembalian = pembayaran - this.hitungTotalBelanja();
        LocalDate tanggal = LocalDate.now();
        DefaultTableModel tableModel = (DefaultTableModel) tabelListBarang.getModel();
        
        if(kembalian>=0){
            try{
                String sql = "INSERT INTO transaksi (tanggal, total_transaksi, diskon) values (?,?,?)";
                PreparedStatement ps = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
                ps.setDate(1, java.sql.Date.valueOf(tanggal));
                ps.setDouble(2, this.hitungTotalBelanja());
                ps.setDouble(3, this.discount);
                ps.executeUpdate();
                ResultSet generatedKey = ps.getGeneratedKeys();
                int idTransaksi = -1;
                if (generatedKey.next()) {
                    idTransaksi = generatedKey.getInt(1);
                }
                
                // memasukkan detail transaksi ke database
                String sql2 = "INSERT INTO detail_transaksi (id_transaksi, kode_barang, jumlah) VALUES(?,?,?)";
                PreparedStatement ps2 = connection.prepareStatement(sql2);
                for(int row=0;row<tableModel.getRowCount();row++){
                    int kodeBarang = Integer.valueOf(tableModel.getValueAt(row, 0).toString());
                    int jumlah = Integer.valueOf(tableModel.getValueAt(row, 4).toString());
                    
                    ps2.setInt(1, generatedKey.getInt(1));
                    ps2.setInt(2, kodeBarang);
                    ps2.setInt(3, jumlah);
                    ps2.executeUpdate();
                }
                
                //menambahkan poin ke tabel member
                if(!(inputIdMember.getText().toString().equals(""))){
                    int idMember = Integer.valueOf(inputIdMember.getText().toString());
                    poin += Integer.valueOf(inputPoin.getText().toString());
                    String sql3 = "UPDATE member SET poin=? WHERE id=?";
                    PreparedStatement ps3 = connection.prepareStatement(sql3);
                    ps3.setInt(1, poin);
                    ps3.setInt(2, idMember);
                    ps3.executeUpdate();
                }
                
                JOptionPane.showMessageDialog(this, "Pembayaran Berhasil", "Success", JOptionPane.INFORMATION_MESSAGE);
                
            }catch(SQLException e){
                System.out.println(e);
            }
        }
        
    }//GEN-LAST:event_buttonBayarActionPerformed

    private void inputPoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPoinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPoinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBayar;
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JTextField inputDiscount;
    private javax.swing.JTextField inputHarga;
    private javax.swing.JTextField inputIdMember;
    private javax.swing.JTextField inputKembalian;
    private javax.swing.JTextField inputKodeBarang;
    private javax.swing.JTextField inputMerk;
    private javax.swing.JTextField inputNamaBarang;
    private javax.swing.JTextField inputPembayaran;
    private javax.swing.JTextField inputPoin;
    private javax.swing.JTextField inputQuantity;
    private javax.swing.JTextField inputTotalBelanja;
    private javax.swing.JTextField inputTotalItem;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JTable tabelListBarang;
    // End of variables declaration//GEN-END:variables
}
